spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: Employee
#          uri: http://localhost:8081
#          predicates:
#            - Path=/employee/**
#        - id: Consumer
#          uri: http://localhost:8082
#          predicates:
#            - Path=/consumer/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka